name: Go-static-analysis
on: [push, pull_request]
jobs:

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: remove deployer container from dockerfile
        run: sed -ie '/End of builder/,+5d' ./docker/userspacecni/Dockerfile
      - name: Build the Docker image
        run: docker build . -f ./docker/userspacecni/Dockerfile -t userspacecni:latest
      - name: run container
        run: docker run --name userspacecni -itd userspacecni:latest bash
      - name: docker copy generated bin api files
        run: docker cp userspacecni:/root/userspace-cni-network-plugin/cnivpp ./

      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # v2.5.2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.52.2
          args: --timeout=20m

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # master

  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      name: Run Hadolint
      with:
       dockerfile: ./docker/userspacecni/Dockerfile
       ignore: DL3008,DL3059

  go-check:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - name: remove deployer container from dockerfile
      run: sed -ie '/End of builder/,+5d' ./docker/userspacecni/Dockerfile
    - name: Build the Docker image
      run: docker build . -f ./docker/userspacecni/Dockerfile -t userspacecni:latest
    - name: run container
      run: docker run --name userspacecni -itd userspacecni:latest bash
    - name: docker copy generated bin api files
      run: docker cp userspacecni:/root/userspace-cni-network-plugin/cnivpp ./

    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: 1.20.1

    - name: checkout dockerfile to avoid false diff
      run: git checkout ./docker/userspacecni/Dockerfile
    # if this fails, run go mod tidy
    - name: Check if module files are consistent with code
      run: go mod tidy && go get go.fd.io/govpp/binapigen/vppapi@v0.7.0 && git diff --exit-code #need package for bin api but not working with tidy

    # if this fails, run go mod vendor
    - name: Check if vendor directory is consistent with go modules
      run: go mod vendor && git diff --exit-code
